num1 = 10
num2 = 2

num3 = 2.5
num4 = 4.5

mensaje = "hola"

suma = num1 + num2
resta = num1 - num2

multiplicacion = num3 * num4
division = num4 / num3

promedio = (num1 + num2) / 2

#print de operaciones matematicas

print("el resultado de la suma es: ", suma)
print(f"el resultado es la resta es: {resta}")
print("el resultado de la division es:", division)
print("el resultado de la multiplicacion es: ", multiplicacion)

# Comparaciones entre los números enteros
es_mayor = num1 > num2  # num1 es mayor que num2
es_igual = num1 == num2  # num1 es igual a num2
es_menor = num1 < num2  # num1 es menor que num2

# Mostrando los resultados de las comparaciones
print("num1 es mayor que num2:", es_mayor)
print("num1 es igual a num2:", es_igual)
print("num1 es menor que num2:", es_menor)